<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net46</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="IllusionLibs.KoikatsuSunshine.AllPackages" Version="*" />
		<PackageReference Include="IllusionLibs.KoikatsuSunshine.MoreAccessories" Version="*">
			<ExcludeAssets>all</ExcludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="ExtensibleSaveFormat.KoikatsuSunshine" Version="16.8.1" />
		<PackageReference Include="Sideloader.KoikatsuSunshine" Version="16.8.1" />
	</ItemGroup>

	<Import Project="..\Core.KK\Koikatsu.projitems" Label="Shared" />
	<Import Project="..\Core.Common\Core.MoreAccessories.projitems" Label="Shared" />
</Project>